// swift-tools-version: 5.9
import PackageDescription
let package = Package(name: "PAIAIME", platforms: [.macOS(.v13)], products: [
    .executable(name: "PAIANativeLab", targets: ["NativeIME"]),
    .executable(name: "PAIAInputMethod", targets: ["InputMethodService"]),
    .executable(name: "paia-benchmark", targets: ["BenchmarkCLI"]),
    .executable(name: "paia-constraints", targets: ["ConstraintCLI"])
], targets: [
    .target(name: "CRimeShim", publicHeadersPath: "include", linkerSettings: [.linkedLibrary("dl"), .linkedLibrary("pthread")]),
    .target(name: "TextBoundary"),
    .target(name: "CIMKContext", publicHeadersPath:"include",cSettings:[.unsafeFlags(["-fobjc-arc","-Werror=protocol","-Werror=mismatched-return-types"])]),
    .target(name: "LexiconCore"),
    .target(name: "SettingsCore"),
    .target(name: "ExpressionCore"),
    .target(name: "SessionCore", dependencies: ["TextBoundary"]),
    .target(name: "ConstraintCore", dependencies: ["SessionCore", "TextBoundary"]),
    .target(name: "EngineBridge", dependencies: ["CRimeShim", "SessionCore", "TextBoundary", "ConstraintCore", "LexiconCore", "SettingsCore"]),
    .target(name: "NativeHost", dependencies: ["EngineBridge", "SessionCore", "TextBoundary", "ConstraintCore", "LexiconCore", "SettingsCore"]),
    .executableTarget(name: "NativeIME", dependencies: ["NativeHost", "EngineBridge", "SettingsCore"]),
    .target(name: "IMKHost", dependencies: ["NativeHost", "EngineBridge", "SessionCore", "SettingsCore", "LexiconCore", "ExpressionCore", "ConstraintCore", "TextBoundary", "CIMKContext"]),
    .executableTarget(name: "InputMethodService", dependencies: ["IMKHost", "EngineBridge", "NativeHost"]),
    .target(name: "IMKTestClient",path:"Tests/IMKTestClient",publicHeadersPath:"include",cSettings:[.unsafeFlags(["-fobjc-arc","-Werror=protocol","-Werror=mismatched-return-types"])]),
    .testTarget(name: "ContextCoreTests",dependencies:["TextBoundary","SessionCore"]),
    .testTarget(name: "ContextIMKTests",dependencies:["IMKHost","IMKTestClient","EngineBridge","SessionCore","TextBoundary","NativeHost"]),
    .testTarget(name: "ExpressionCoreTests", dependencies: ["ExpressionCore", "SessionCore"]),
    .testTarget(name: "ExpressionIMKTests", dependencies: ["ExpressionCore", "IMKHost", "IMKTestClient", "EngineBridge", "SessionCore"]),
    .testTarget(name: "IMKRepairTests",dependencies:["IMKHost","IMKTestClient","EngineBridge","SessionCore"]),
    .testTarget(name: "IMKBasicTests",dependencies:["IMKHost","IMKTestClient","EngineBridge","NativeHost","SettingsCore","LexiconCore","SessionCore"]),
    .testTarget(name: "IMKProtocolTests",dependencies:["IMKHost","IMKTestClient","EngineBridge","SessionCore"]),
    .executableTarget(name: "BenchmarkCLI", dependencies: ["EngineBridge", "SessionCore"]),
    .executableTarget(name: "ConstraintCLI", dependencies: ["EngineBridge", "SessionCore", "ConstraintCore"]),
    .testTarget(name: "SettingsRecoveryTests", dependencies: ["SettingsCore"]),
    .testTarget(name: "SettingsRecoveryHostTests", dependencies: ["SettingsCore", "NativeHost", "EngineBridge"]),
    .testTarget(name: "KeyboardSafetyTests", dependencies: ["NativeHost", "EngineBridge", "SessionCore"]),
    .testTarget(name: "CharacterCoreTests", dependencies: ["TextBoundary", "SessionCore"]),
    .testTarget(name: "CharacterHostTests", dependencies: ["NativeHost", "EngineBridge", "SessionCore", "TextBoundary", "SettingsCore"]),
    .testTarget(name: "CandidateOverflowTests", dependencies: ["NativeHost", "EngineBridge", "SessionCore", "LexiconCore"]),
    .testTarget(name: "CandidateNavigationTests", dependencies: ["NativeHost", "EngineBridge", "SessionCore"]),
    .testTarget(name: "NativeControlTests", dependencies: ["NativeHost", "EngineBridge", "SessionCore", "ConstraintCore"]),
    .testTarget(name: "LexiconCoreTests", dependencies: ["LexiconCore"]),
    .testTarget(name: "SettingsCoreTests", dependencies: ["SettingsCore"]),
    .testTarget(name: "SettingsNativeTests", dependencies: ["SettingsCore", "NativeHost", "EngineBridge", "LexiconCore"]),
    .testTarget(name: "PersonalControlTests", dependencies: ["NativeHost", "LexiconCore"]),
    .testTarget(name: "PersonalEngineTests", dependencies: ["LexiconCore", "EngineBridge", "NativeHost"]),
    .testTarget(name: "ConstraintCoreTests", dependencies: ["ConstraintCore", "SessionCore"]),
    .testTarget(name: "ConstraintHostTests", dependencies: ["ConstraintCore", "EngineBridge", "NativeHost"]),
    .testTarget(name: "SessionCoreTests", dependencies: ["SessionCore", "TextBoundary"]),
    .testTarget(name: "EngineTests", dependencies: ["EngineBridge", "SessionCore"]),
    .testTarget(name: "AppKitHostTests", dependencies: ["NativeHost", "EngineBridge", "SessionCore"])
])
