/* Synthetic interaction specimen. No network, localStorage, OS hooks or PAIA calls. */
'use strict';
const $=id=>document.getElementById(id), K=IMEStudy, s=new K.Session(), sink=new K.EffectSink();
let english=false, scene='typing', editEpoch=1, target=1, lastSelection='', lease=null, recallBookmark=null, assistSequence=0, activeResult=0, currentResults=[], onStep=0, savedCounter=0, activeSegment=1;
const initial='明天把实验报告发给林小棠。\n\n关于形状因子的讨论，先保留已经验证的部分。\n';
const baselineExpressions=[
{id:'e1',text:'请先核实事实，区分已经证实、合理推测和仍待验证的部分。不要把假设写成结论。',title:'核实事实，再给结论',source:'手动收藏 · 虚构样例',tags:'事实 heshi shishi 规则 guize'},
{id:'e2',text:'保持原文中的数字、专有名词和否定关系不变。只修正明确的错字，不替我改写立场。',title:'只改错字，不改变立场',source:'手动收藏 · 虚构样例',tags:'错字 cuozi 规则 guize'},
{id:'e3',text:'本轮只做研究和方案比较，不修改代码、不增加权限，也不进行正式部署。',title:'本轮只研究，不实施',source:'手动收藏 · 虚构样例',tags:'研究 yanjiu 实施 权限'},
{id:'e4',text:'请保留已经正确的部分，只修正与当前问题有关的词段。不要因为一次修改而重新组织整篇内容。',title:'局部修改，保留其余',source:'手动收藏 · 虚构样例',tags:'修改 xiugai 局部'},
{id:'e5',text:'先说明当前证据实际支持什么，再说明无法据此推出什么。最后给出最小必要的下一步验证。',title:'证据边界与下一步',source:'手动收藏 · 虚构样例',tags:'证据 zhengju 验证 yanzheng'}
];
let expressions=baselineExpressions.map(x=>({...x}));
const segments=[{text:'我在',options:['我在','我再']},{text:'研究',options:['研究','烟酒','研修']},{text:'形状因子',options:['形状因子','形状音字']}];
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>{$('toast').hidden=true;},2800);}
function syncSelection(){const d=$('draft'),now=`${d.selectionStart}:${d.selectionEnd}`;if(now!==lastSelection){lastSelection=now;editEpoch++;}}
function current(){syncSelection();const d=$('draft');return {target,epoch:editEpoch,privacy:s.privacyEpoch,text:d.value,start:d.selectionStart,end:d.selectionEnd};}
function setDraft(text,start=text.length,end=start){$('draft').value=text;editEpoch++;$('draft').setSelectionRange(start,end);lastSelection=`${start}:${end}`;}
function hide(id){$(id).hidden=true;if(id==='assistPanel'){assistSequence++;lease=null;$('originalText').textContent='';$('revisedText').textContent='';delete $('revisedText').dataset.result;$('assistStatus').textContent='';}if(id==='recallPanel'){recallBookmark=null;$('query').value='';$('results').replaceChildren();$('expressionPreview').textContent='';}if(id==='saveModal')$('saveText').value='';}
function closeAll(){for(const id of ['candidatePanel','recallPanel','assistPanel','settingsModal','onboardModal','saveModal'])hide(id);}
function position(id){const p=$(id);if(p.hidden)return;const r=$('raw').getBoundingClientRect();const size={width:p.getBoundingClientRect().width,height:p.getBoundingClientRect().height};const xy=K.placePanel({x:r.left+Math.min(50,r.width/3),y:r.top,height:r.height},size,{x:0,y:0,width:innerWidth,height:innerHeight});if(!xy)return;p.style.left=xy.x+'px';p.style.top=xy.y+'px';}
function show(id){$(id).hidden=false;position(id);}
function renderCandidates(){
 $('candidateList').replaceChildren();$('preedit').textContent=s.raw;$('stateLabel').textContent=s.raw?'组字中':s.privateMode?'私密输入':english?'英文直输':'准备输入';
 if(!s.raw||english||scene==='repair'||!s.snapshot||!$('recallPanel').hidden||!$('assistPanel').hidden){$('candidatePanel').hidden=true;return;}
 s.snapshot.rows.slice(0,5).forEach((r,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('role','option');b.setAttribute('aria-selected',String(i===s.highlight));const n=document.createElement('span');n.className='idx';n.textContent=i+1;b.append(n,document.createTextNode(r.text));b.addEventListener('mousedown',e=>e.preventDefault());b.addEventListener('click',()=>consume(s.choose(i)));$('candidateList').append(b);});show('candidatePanel');
}
function decode(){const r=s.setRaw($('raw').value,$('raw').selectionStart||0);if(!r.ok){s.cancel();toast('演示输入上限为512个字符；已保留原始文字。');$('candidatePanel').hidden=true;return;}s.refresh();renderCandidates();}
function consume(effect){if(!effect)return;const d=$('draft');sink.apply(effect,s.targetEpoch,text=>{const start=d.selectionStart,end=d.selectionEnd;setDraft(d.value.slice(0,start)+text+d.value.slice(end),start+text.length);});$('raw').value='';$('candidatePanel').hidden=true;$('raw').focus();renderCandidates();}
function privateMode(on){s.privacy(on);$('privateSetting').checked=on;$('privacyLabel').textContent=on?'私密 · 不学习、不调用表达':'仅本页内存';hide('recallPanel');hide('assistPanel');hide('saveModal');s.refresh();renderCandidates();}
function canEnhance(){if(s.privateMode){toast('私密输入中不读取个人表达、不保存、不使用辅助处理。');return false;}if($('raw').value){toast('请先完成或取消当前组字；本原型不会替你自动上屏。');return false;}return true;}
function openRecall(){if(!canEnhance())return;hide('assistPanel');$('candidatePanel').hidden=true;recallBookmark={...current(),expires:performance.now()+30000};activeResult=0;$('query').value='';renderExpressions();show('recallPanel');$('query').focus({preventScroll:true});}
function renderExpressions(){const q=$('query').value.trim().toLowerCase();currentResults=expressions.filter(e=>(e.title+' '+e.text+' '+e.tags).toLowerCase().includes(q));activeResult=Math.max(0,Math.min(activeResult,currentResults.length-1));$('results').replaceChildren();for(let i=0;i<currentResults.length;i++){const e=currentResults[i],b=document.createElement('button');b.type='button';b.className='result';b.setAttribute('role','option');b.setAttribute('aria-selected',String(i===activeResult));const a=document.createElement('strong');a.textContent=e.title;const small=document.createElement('small');small.textContent=e.source;b.append(a,small);b.addEventListener('click',()=>{activeResult=i;renderExpressions();});$('results').append(b);}if(!currentResults.length){const p=document.createElement('p');p.className='empty';p.textContent='没有找到已保存的表达。不会生成一段话冒充原话。';$('results').append(p);}$('expressionPreview').textContent=currentResults[activeResult]?.text||'';$('insertExpression').disabled=!currentResults.length;$('insertExpression').textContent=recallBookmark&&recallBookmark.end>recallBookmark.start?'替换所选文字':'插入完整原话';$('deleteExpression').disabled=!currentResults.length;position('recallPanel');}
function insertExpression(){const item=currentResults[activeResult],c=current(),b=recallBookmark;if(!item||!b||s.privateMode||performance.now()>=b.expires||!['target','epoch','privacy','text','start','end'].every(k=>c[k]===b[k])){toast('目标文字或选区已经改变，请重新调用。');return;}setDraft(c.text.slice(0,c.start)+item.text+c.text.slice(c.end),c.start+item.text.length);hide('recallPanel');$('draft').focus();toast('已插入完整原话；没有发送。');}
function beginAssist(){if(!canEnhance())return;hide('recallPanel');const c=current();lease=K.makeLease({...c,now:performance.now()});if(!lease){toast('请先在演示文稿中选中要修改的文字。');return;}const original=c.text.slice(c.start,c.end);$('originalText').textContent=original;$('revisedText').textContent='';$('applyAssist').disabled=true;$('assistStatus').textContent='等待固定演示结果…';show('assistPanel');const token=++assistSequence;if($('modelUnavailable').checked){$('assistStatus').textContent='模型不可用（演示）。原文未改动，也不会自动改用云服务。';return;}
 setTimeout(()=>{if(token!==assistSequence||!lease||s.privateMode)return;const revised=original.replaceAll('实脸','实验');$('revisedText').replaceChildren();if(revised!==original){const pieces=revised.split('实验');pieces.forEach((p,i)=>{if(i){const m=document.createElement('mark');m.className='diff';m.textContent='实验';$('revisedText').append(m);}$('revisedText').append(document.createTextNode(p));});}else $('revisedText').textContent=revised;$('revisedText').dataset.result=revised;$('assistStatus').textContent=revised===original?'这个固定示例没有可修改的“实脸”。不生成其它变化。':'仅演示“实脸 → 实验”；数字与末句否定保持原样。';$('applyAssist').disabled=revised===original;position('assistPanel');},450);
}
function applyAssist(){const result=$('revisedText').dataset.result||'',c=current(),next=K.applyLease(lease,c,result,performance.now());if(next===null){$('assistStatus').textContent='原文、选区或目标已改变。拒绝应用旧结果；请重新选择。';$('applyAssist').disabled=true;return;}const end=lease.start+result.length;setDraft(next,end);hide('assistPanel');$('draft').focus();toast('已应用这一次修改；没有发送。');}
function renderRepair(){const selected=segments[activeSegment];$('segments').replaceChildren();segments.forEach((seg,i)=>{const b=document.createElement('button');b.className='segment';b.textContent=seg.text;b.setAttribute('aria-pressed',String(i===activeSegment));b.addEventListener('click',()=>{activeSegment=i;renderRepair();});$('segments').append(b);});$('repairchoices').replaceChildren();selected.options.forEach((text,i)=>{const b=document.createElement('button');b.textContent=`${i+1} ${text}`;b.addEventListener('click',()=>{selected.text=text;renderRepair();});$('repairchoices').append(b);});}
function setScene(which){closeAll();s.targetChanged();target++;editEpoch++;scene=which;english=false;$('mode').textContent='中';$('raw').value='';s.privacy(false);$('privateSetting').checked=false;$('privacyLabel').textContent='仅本页内存';$('repair').hidden=which!=='repair';$('rawline').hidden=which==='repair';setDraft(initial);document.querySelectorAll('[data-scene]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.scene===which)));const copy={typing:['日常输入，不需要思考输入法。','普通候选不等待大模型。示例只支持少量固定词组，不能用它评价转换准确率。'],repair:['改错一个词，不必牺牲后半句。','点击词段，仅改变该段；两侧已确认文字保持原样。Option + 左右可以移动词段，数字键选择。真实引擎约束仍待验证。'],recall:['把你说过的话，带回当前表达。','显式查询自己的收藏。结果是原话，不是AI生成的相似表述；插入会保留完整末句。'],assist:['需要修改时，再请它介入。','只处理明确选中的文本，先看差异再应用。修改期间移动选区或更改原文，旧结果必须失效。'],private:['依然能打字，不留下新的记录。','演示暂停个人词条、收藏调用、学习和辅助处理。并非自动识别真实密码或无痕窗口的证明。']};$('sideTitle').textContent=copy[which][0];$('sideText').textContent=copy[which][1];$('inlineHint').textContent=which==='repair'?'未上屏组字的修正示例；不是对任意宿主已成文文本进行重转。':'普通输入没有 AI 按钮，没有历史信息流，也不等待模型。';
 if(which==='repair'){segments[0].text='我在';segments[1].text='研究';segments[2].text='形状因子';activeSegment=1;renderRepair();$('segments').querySelectorAll('button')[1].focus();}
 else if(which==='recall'){openRecall();}
 else if(which==='assist'){const t='请检查实脸报告，预算为12.5万元，不要改变结论。';setDraft(t,0,t.length);beginAssist();}
 else {privateMode(which==='private');$('raw').focus();}renderCandidates();
}
function openSettings(){hide('candidatePanel');$('settingsModal').hidden=false;$('settingsModal').querySelector('button').focus();}
function renderOnboard(){const pages=[['先安心打字。','基础输入在本机运行，不要求账号。个人学习、语音、AI修改和PAIA连接分别选择。'],['由你在系统里启用。','正式产品会引导你进入系统设置 → 键盘 → 输入法，添加输入源。本网页不改变系统配置，也不代你同意权限。'],['试一次，再开始。','完成启用后，先体验输入、选词、取消和中英文切换。不需要先选一个AI模型。']];$('onstep').textContent=`${onStep+1} / 3 · 安装引导演示`;$('oncontent').replaceChildren();const h=document.createElement('h2');h.textContent=pages[onStep][0];const p=document.createElement('p');p.textContent=pages[onStep][1];$('oncontent').append(h,p);$('onback').disabled=onStep===0;$('onnext').textContent=onStep===2?'开始试打':'继续';}
$('draft').addEventListener('input',()=>{editEpoch++;syncSelection();});$('draft').addEventListener('select',syncSelection);
let nativeComposing=false;$('raw').addEventListener('compositionstart',()=>{nativeComposing=true;hide('candidatePanel');});$('raw').addEventListener('compositionend',()=>{nativeComposing=false;decode();});$('raw').addEventListener('input',()=>{if(!nativeComposing)decode();});
$('raw').addEventListener('keydown',e=>{if(nativeComposing||e.isComposing||e.metaKey||e.ctrlKey)return;if(e.altKey&&e.code==='Space'){e.preventDefault();openRecall();return;}if(english){if(e.key==='Enter'&&$('raw').value){e.preventDefault();s.setRaw($('raw').value);consume(s.commit(s.raw));}return;}if(!s.raw)return;if(e.key===' '){e.preventDefault();consume(s.choose());}else if(e.key==='Enter'){e.preventDefault();consume(s.commit(s.raw));}else if(/^[1-5]$/.test(e.key)){e.preventDefault();consume(s.choose(Number(e.key)-1));}else if(['ArrowDown','ArrowUp','Tab'].includes(e.key)){e.preventDefault();s.step(e.key==='ArrowUp'||(e.key==='Tab'&&e.shiftKey)?-1:1);renderCandidates();}else if(e.key==='Escape'){e.preventDefault();s.cancel();$('raw').value='';renderCandidates();}});
$('raw').addEventListener('keyup',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)&&s.raw)decode();});
$('query').addEventListener('input',()=>{activeResult=0;renderExpressions();});$('query').addEventListener('keydown',e=>{if(e.isComposing)return;if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();activeResult=currentResults.length?(activeResult+(e.key==='ArrowDown'?1:-1)+currentResults.length)%currentResults.length:0;renderExpressions();}if(e.key==='Enter'){e.preventDefault();insertExpression();}});
$('repair').addEventListener('keydown',e=>{if(e.altKey&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();activeSegment=(activeSegment+(e.key==='ArrowRight'?1:-1)+segments.length)%segments.length;renderRepair();$('segments').querySelectorAll('button')[activeSegment].focus();}else if(/^[1-3]$/.test(e.key)&&!e.metaKey&&!e.ctrlKey){const t=segments[activeSegment].options[Number(e.key)-1];if(t){e.preventDefault();segments[activeSegment].text=t;renderRepair();}}});
$('commitRepair').onclick=()=>{const t=segments.map(s=>s.text).join(''),d=$('draft');setDraft(d.value.slice(0,d.selectionStart)+t+d.value.slice(d.selectionEnd));$('repair').hidden=true;$('rawline').hidden=false;scene='typing';toast('示例整句已上屏；没有发送。');$('raw').focus();};$('resetRepair').onclick=()=>{segments[0].text='我在';segments[1].text='研究';segments[2].text='形状因子';renderRepair();};$('cancelRepair').onclick=()=>setScene('typing');
$('openRecall').onclick=openRecall;$('openAssist').onclick=beginAssist;$('applyAssist').onclick=applyAssist;$('insertExpression').onclick=insertExpression;$('deleteExpression').onclick=()=>{const e=currentResults[activeResult];if(e){expressions=expressions.filter(x=>x.id!==e.id);renderExpressions();toast('已从本页示例中移除。');}};
$('saveSelection').onclick=()=>{if(!canEnhance())return;const c=current();if(c.start===c.end){toast('请先选中要保存的表达。');return;}$('saveText').value=c.text.slice(c.start,c.end);$('saveModal').hidden=false;$('saveText').focus();};$('confirmSave').onclick=()=>{if(s.privateMode)return;const text=$('saveText').value;if(!text.trim()){toast('不能保存空白表达。');return;}expressions.push({id:'saved'+(++savedCounter),text,title:text.slice(0,26),source:'本页手动保存 · 未发送确认',tags:''});hide('saveModal');toast('只保存了本次确认的表达；刷新后清空。');};
$('settings').onclick=openSettings;$('privateSetting').onchange=e=>privateMode(e.target.checked);$('clearSaved').onclick=()=>{expressions=expressions.filter(x=>!x.id.startsWith('saved'));toast('本页手动保存已清空；虚构样例保留。');};$('largeText').onchange=e=>{$('draft').style.fontSize=e.target.checked?'26px':'';};
$('mode').onclick=()=>{if(s.raw){toast('请先完成当前组字，再切换输入模式。');return;}english=!english;$('mode').textContent=english?'英':'中';renderCandidates();$('raw').focus();};
$('theme').onclick=()=>{const dark=document.documentElement.dataset.theme!=='dark';document.documentElement.dataset.theme=dark?'dark':'light';$('theme').textContent=dark?'浅色':'深色';};
$('onboarding').onclick=()=>{hide('candidatePanel');onStep=0;renderOnboard();$('onboardModal').hidden=false;$('onnext').focus();};$('onnext').onclick=()=>{if(onStep<2){onStep++;renderOnboard();}else{hide('onboardModal');setScene('typing');}};$('onback').onclick=()=>{onStep=Math.max(0,onStep-1);renderOnboard();};
$('drift').onclick=()=>{setDraft($('draft').value+'\n宿主新增加的一句。');toast('宿主文字已改变（模拟）。');};$('targetDrift').onclick=()=>{target++;editEpoch++;s.targetChanged();$('raw').value='';renderCandidates();toast('输入目标已改变（模拟）。');};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{hide(b.dataset.close);$('raw').focus();renderCandidates();});document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>setScene(b.dataset.scene));document.querySelectorAll('[data-sample]').forEach(b=>b.onclick=()=>{setScene('typing');$('raw').value=b.dataset.sample;$('raw').setSelectionRange(b.dataset.sample.length,b.dataset.sample.length);decode();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){const modal=['saveModal','settingsModal','onboardModal','assistPanel','recallPanel'].find(id=>!$(id).hidden);if(modal){e.preventDefault();hide(modal);$('raw').focus();renderCandidates();}}const m=['saveModal','settingsModal','onboardModal'].find(id=>!$(id).hidden);if(e.key==='Tab'&&m){const list=[...$(m).querySelectorAll('button:not(:disabled),input,textarea,select')].filter(e=>!e.hidden),first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.addEventListener('resize',()=>['candidatePanel','recallPanel','assistPanel'].forEach(position));window.addEventListener('scroll',()=>['candidatePanel','recallPanel','assistPanel'].forEach(position),true);
setDraft(initial);renderCandidates();
